
# This file is automatically generated, you probably don't want to edit this

corrInspectOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrInspectOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = "allVsAll",
            vars = NULL,
            refVar = NULL,
            compareVars = NULL,
            refAxis = "x",
            pearson = TRUE,
            spearman = FALSE,
            kendall = FALSE,
            hypothesis = "corr",
            sig = TRUE,
            flag = FALSE,
            n = FALSE,
            ci = FALSE,
            ciWidth = 95,
            plots = FALSE,
            plotDens = FALSE, ...) {

            super$initialize(
                package="corrInspect",
                name="corrInspect",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "allVsAll",
                    "refVsRest"),
                default="allVsAll")
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..refVar <- jmvcore::OptionVariable$new(
                "refVar",
                refVar,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..compareVars <- jmvcore::OptionVariables$new(
                "compareVars",
                compareVars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)
            private$..refAxis <- jmvcore::OptionList$new(
                "refAxis",
                refAxis,
                options=list(
                    "x",
                    "y"),
                default="x")
            private$..pearson <- jmvcore::OptionBool$new(
                "pearson",
                pearson,
                default=TRUE)
            private$..spearman <- jmvcore::OptionBool$new(
                "spearman",
                spearman,
                default=FALSE)
            private$..kendall <- jmvcore::OptionBool$new(
                "kendall",
                kendall,
                default=FALSE)
            private$..hypothesis <- jmvcore::OptionList$new(
                "hypothesis",
                hypothesis,
                options=list(
                    "corr",
                    "pos",
                    "neg"),
                default="corr")
            private$..sig <- jmvcore::OptionBool$new(
                "sig",
                sig,
                default=TRUE)
            private$..flag <- jmvcore::OptionBool$new(
                "flag",
                flag,
                default=FALSE)
            private$..n <- jmvcore::OptionBool$new(
                "n",
                n,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..plots <- jmvcore::OptionBool$new(
                "plots",
                plots,
                default=FALSE)
            private$..plotDens <- jmvcore::OptionBool$new(
                "plotDens",
                plotDens,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..vars)
            self$.addOption(private$..refVar)
            self$.addOption(private$..compareVars)
            self$.addOption(private$..refAxis)
            self$.addOption(private$..pearson)
            self$.addOption(private$..spearman)
            self$.addOption(private$..kendall)
            self$.addOption(private$..hypothesis)
            self$.addOption(private$..sig)
            self$.addOption(private$..flag)
            self$.addOption(private$..n)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..plots)
            self$.addOption(private$..plotDens)
        }),
    active = list(
        mode = function() private$..mode$value,
        vars = function() private$..vars$value,
        refVar = function() private$..refVar$value,
        compareVars = function() private$..compareVars$value,
        refAxis = function() private$..refAxis$value,
        pearson = function() private$..pearson$value,
        spearman = function() private$..spearman$value,
        kendall = function() private$..kendall$value,
        hypothesis = function() private$..hypothesis$value,
        sig = function() private$..sig$value,
        flag = function() private$..flag$value,
        n = function() private$..n$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        plots = function() private$..plots$value,
        plotDens = function() private$..plotDens$value),
    private = list(
        ..mode = NA,
        ..vars = NA,
        ..refVar = NA,
        ..compareVars = NA,
        ..refAxis = NA,
        ..pearson = NA,
        ..spearman = NA,
        ..kendall = NA,
        ..hypothesis = NA,
        ..sig = NA,
        ..flag = NA,
        ..n = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..plots = NA,
        ..plotDens = NA)
)

corrInspectResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrInspectResults",
    inherit = jmvcore::Group,
    active = list(
        tableAllVsAll = function() private$.items[["tableAllVsAll"]],
        tableRefVsRest = function() private$.items[["tableRefVsRest"]],
        plotAllVsAll = function() private$.items[["plotAllVsAll"]],
        plotRefVsRest = function() private$.items[["plotRefVsRest"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Inspector")
            self$add(jmvcore::Table$new(
                options=options,
                name="tableAllVsAll",
                title="Correlations",
                visible="(mode:allVsAll)",
                clearWith=list(
                    "vars",
                    "pearson",
                    "spearman",
                    "kendall",
                    "hypothesis",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="var2", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="stat", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="r", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci", 
                        `title`="95% CI", 
                        `type`="text", 
                        `visible`="(ci)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer", 
                        `visible`="(n)"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(sig)"),
                    list(
                        `name`="stars", 
                        `title`="", 
                        `type`="text", 
                        `visible`="(flag)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableRefVsRest",
                title="Correlations",
                visible="(mode:refVsRest)",
                clearWith=list(
                    "refVar",
                    "compareVars",
                    "pearson",
                    "spearman",
                    "kendall",
                    "hypothesis",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var2", 
                        `title`="Compared with", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="stat", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="r", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci", 
                        `title`="95% CI", 
                        `type`="text", 
                        `visible`="(ci)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer", 
                        `visible`="(n)"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(sig)"),
                    list(
                        `name`="stars", 
                        `title`="", 
                        `type`="text", 
                        `visible`="(flag)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotAllVsAll",
                title="Scatterplot",
                visible=FALSE,
                requiresData=TRUE,
                renderFun=".plotAllVsAll",
                clearWith=list(
                    "vars",
                    "pearson",
                    "spearman",
                    "kendall",
                    "ci",
                    "ciWidth",
                    "plotDens",
                    "mode")))
            self$add(jmvcore::Array$new(
                options=options,
                name="plotRefVsRest",
                title="Scatterplots",
                visible=FALSE,
                template=jmvcore::Image$new(
                    options=options,
                    renderFun=".plotRefVsRest",
                    requiresData=TRUE),
                clearWith=list(
                    "refVar",
                    "compareVars",
                    "refAxis",
                    "pearson",
                    "ci",
                    "ciWidth",
                    "plotDens",
                    "mode")))}))

corrInspectBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corrInspectBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "corrInspect",
                name = "corrInspect",
                version = c(1,0,0),
                options = options,
                results = corrInspectResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Correlation Inspector
#'
#' Correlations between two or more variables, presented pair by pair instead 
#' of as a matrix. With exactly two variables this is a single clean result. 
#' With more, choose between comparing all variables against all others, or 
#' one reference variable against the rest -- useful for inspecting candidate 
#' predictors or confounders before a regression.
#' 
#'
#' @examples
#' corrInspect::corrInspect(data = mtcars, vars = c('mpg', 'hp', 'wt'))
#'
#' @param data the data as a data frame
#' @param mode \code{'allVsAll'} (default) or \code{'refVsRest'}, which
#'   comparison layout to use
#' @param vars a vector of strings naming the variables to correlate pairwise
#'   in \code{data}
#' @param refVar a string naming the reference variable in \code{data}
#' @param compareVars a vector of strings naming the variables in \code{data}
#'   to compare against \code{refVar}
#' @param refAxis \code{'x'} (default) or \code{'y'}, which axis the reference
#'   variable is plotted on
#' @param pearson \code{TRUE} (default) or \code{FALSE}, provide Pearson's r
#' @param spearman \code{TRUE} or \code{FALSE} (default), provide Spearman's
#'   rho
#' @param kendall \code{TRUE} or \code{FALSE} (default), provide Kendall's
#'   tau-b
#' @param hypothesis one of \code{'corr'} (default), \code{'pos'},
#'   \code{'neg'} specifying the alternative hypothesis; correlated, correlated
#'   positively, correlated negatively respectively
#' @param sig \code{TRUE} (default) or \code{FALSE}, provide a p-value for
#'   each correlation
#' @param flag \code{TRUE} or \code{FALSE} (default), flag significant
#'   correlations (p < .05) with an asterisk
#' @param n \code{TRUE} or \code{FALSE} (default), provide the number of cases
#' @param ci \code{TRUE} or \code{FALSE} (default), provide a confidence
#'   interval for Pearson's r
#' @param ciWidth a number between 50 and 99.9 (default 95), the confidence
#'   interval width
#' @param plots \code{TRUE} or \code{FALSE} (default), provide annotated
#'   scatterplot(s)
#' @param plotDens \code{TRUE} or \code{FALSE} (default), add marginal
#'   densities to the scatterplot(s)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tableAllVsAll} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableRefVsRest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotAllVsAll} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotRefVsRest} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableAllVsAll$asDF}
#'
#' \code{as.data.frame(results$tableAllVsAll)}
#'
#' @export
corrInspect <- function(
    data,
    mode = "allVsAll",
    vars = NULL,
    refVar = NULL,
    compareVars = NULL,
    refAxis = "x",
    pearson = TRUE,
    spearman = FALSE,
    kendall = FALSE,
    hypothesis = "corr",
    sig = TRUE,
    flag = FALSE,
    n = FALSE,
    ci = FALSE,
    ciWidth = 95,
    plots = FALSE,
    plotDens = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("corrInspect requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(refVar)) refVar <- jmvcore::resolveQuo(jmvcore::enquo(refVar))
    if ( ! missing(compareVars)) compareVars <- jmvcore::resolveQuo(jmvcore::enquo(compareVars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(refVar), refVar, NULL),
            `if`( ! missing(compareVars), compareVars, NULL))


    options <- corrInspectOptions$new(
        mode = mode,
        vars = vars,
        refVar = refVar,
        compareVars = compareVars,
        refAxis = refAxis,
        pearson = pearson,
        spearman = spearman,
        kendall = kendall,
        hypothesis = hypothesis,
        sig = sig,
        flag = flag,
        n = n,
        ci = ci,
        ciWidth = ciWidth,
        plots = plots,
        plotDens = plotDens)

    analysis <- corrInspectClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

